# -*- coding: utf-8 -*-
"""exam15_k_means_clustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NgYqQHkyLxGLnwwcylflxm-GyUzXzooC
"""

import pandas as pd
import matplotlib.pyplot as plt
import scipy.cluster.hierarchy as shc
from sklearn.preprocessing import normalize
from sklearn.cluster import KMeans

data = pd.read_csv('./datasets/wholesale.csv')
print(data.head())

data_scaled = normalize(data)
data_scaled = pd.DataFrame(data_scaled, columns=data.columns)
print(data_scaled.head())

plt.figure(figsize=(5,4))
plt.title('Dendrograms')
shc.dendrogram(shc.linkage(data_scaled, method='ward'))
plt.axhline(y=4, color='r', linestyle='--')
plt.show()

cluster = KMeans(n_clusters=4)
print(cluster.fit_predict(data_scaled))

plt.figure(figsize=(5,4))
plt.scatter(data_scaled['Milk'], data_scaled['Grocery'], c=cluster.labels_)
plt.show()

pd.plotting.scatter_matrix(data_scaled, figsize=(15,15), c=cluster.labels_)
plt.show()

