# -*- coding: utf-8 -*-
"""exam03_control_3.ipynb의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nfgaw0oekJz5rx8_s_UEakq8pv4C-c8t

#제어문

##분기문 **if**
"""

money = 8000
if money > 5000:
    print('택시타고 가요~~')
    print('음료를 사먹어요')
else:
    print('걸어가요')
    print('더워요, 샤워할래요')

money = 8000
if 1000 < money <= 5000:
    print('버스를 타고 가요')

if money > 1000 and money <= 5000:
    print('버스를 타고 가요')

money = 6000
card = False
if (money > 5000) or card:
    print('택시를 타고 가요')
else :
    print('걸어가요')

money = 8000
if money < 2000:
    print('걸어가요')
elif money <= 5000:
    print('버스를 타요')
else:
    print('택시를 타요')
print('end')

money = 1000
if money < 2000:
    print('걸어가요')
else:
    if money <= 5000:
        print('버스를 타요')
    else:
        print('택시를 타요')

money = 10000
time = 5
if money < 5000:
    if time > 30:
        print('걸어가요')
    else:
        print('뛰어가요')
else:
    if time < 10:
        print('택시를 타요')
    else :
        print('버스를 타요')

money = 10000
time = 8
if money < 5000 and time > 30:
    print('걸어가요')
elif money < 5000 and time <= 30:
    print('뛰어가요')
elif money >= 5000 and time < 10:
    print('택시를 타요')
else :
    print('버스를 타요')

money = 10000
if money:
    print('%d원을 기부합니다.' % money)

money = '10000'
if money :
    print('%s원을 기부합니다.' % money)

pocket = ['paper', 'cellphone', 'money']
if 'money' in pocket:
    print('택시를 타요')
elif 'cellphone' in pocket:
    print('택시를 타요')
else :
    print('걸어가요')

if 'money' in pocket:
    pass
else :
    print('일자리를 구해요')

if 'money' not in pocket:
    print('일자리를 구해요')

if 'money' in pocket: pass
else :print('일자리를 구해요')

score = 60
message = 'success' if score >= 60 else 'failure'
print(message)

"""##print 함수"""

a = 20
print(a)

print('a는', a,  '입니다')

print('a는 10진수로 %d 입니다' % a)

print('a는 16진수로 %x 입니다' % a)

print('a는 8진수로 %o 입니다' % a)

b = 'A'
print('b는 %s 입니다' % b)

c = 'c'
print('c는 %c 입니다' % c)

char_var = chr(86)

print('%c' % char_var)

a = 10
b = 20
c = 30
print('a는 %d b는 %d c는 %d' % (a, b, c))

print('a는 {1} b는 {2} c는 {0}'.format(a, b, c))

"""##반복문

###while
"""

sum = 0
number = 0

while sum < 10000:
    number += 1
    sum += number

print(number)
print(sum)

prompt = """
1. Add
2. Del
3. List
4. Quit

Enter number: 
"""

number = 0
user_list = []
while number != '4':
    print(prompt)
    number = input()
    if number == '1':
        user_list.append(
            input("리스트에 추가할 값을 입력하세요"))
    elif number == '2':
        user_list.pop()
    elif number == '3':
        print(user_list)
    elif number == '4':
        pass
    else:
        print('1 ~ 4 중에 고르세요')

print('end')

str_input = input('생년월일을 입력하세요.(YYYYMMDD)\n')
print("%s년 %s월 %s일생입니다." % (
    str_input[:4], str_input[4:6], str_input[6:]))
print(type(str_input))

sum = 0
number = 0

while sum < 6000:
    number += 1
    sum += number
    if number >= 100:
        break
print(sum)
print(number)

sum = 0
number = 0

while number <= 99:
    number += 1
    if number % 2 == 1:
        continue
    sum += number

print(sum)

sum = 0
number = 0

while number <= 99:
    number += 2
    sum += number
    print(sum, end=" ")

while a < 10 or a > 1:
    if input() == 'c':
        break
    print('c를 눌러야 while문을 빠져 나갑니다.')
print('빠져 나왔네요')

number = 0
while True:
    number += 1
    print('%d 무한 반복, 프로그램 안끝남' % number)


sum = 0
홍길동의_점수 = [70,80,90]
for i in rnage(1,142):
    print(i)
    sum += i
print(i)
print(sum)

print(list(range(5)))
print(list(range(2, 5)))
print(list(range(1, 30, 4)))

sum = 0
for i in range(0, 101, 2):
    sum += i
print(sum)

marks = [90, 25, 67, 45, 80]
number = 0
for index, mark in enumerate(marks):
    #number += 1
    if mark < 60:
        continue
    print('%d번 학생 합격입니다.' % (index+1))

marks = [90, 25, 67, 45, 80]
print(list(enumerate(marks)))

a, b = (10, 20)
print(a)
print(b)

for i in range(1,11):
    for j in range(i):
        print('*', end='')
    print()

print("*", end='\n')
print("*", end='A')
print("*", end='3')
print()
print("*", end=' ')
print("*", end=' ')
print("*", end=' ')
print("*", end=' ')

for i in range(1,11):
    for j in range(11-i):
        print('*', end='')
    print()

for i in range(10,0, -1):
    for j in range(i):
        print('*', end='')
    print()

for i in range(1,11):
    for j in range(10-i):
        print(' ', end='')
    for k in range(i):
        print('*', end='')   
    print()

for i in range(1,11) :
  print(" " * (10-i), end = "")
  print("*" * i)

for i in range(1,11):
    for j in range(i-1):
        print(' ', end='')
    for j in range(11-i):
        print('*', end='')
    print()

for i in range(1,11):
    for j in range(10-i):
        print(' ', end='')
    for k in range(i):
        print('*', end='')
    for j in range(i-1):
        print('*', end='')   
    print()
for i in range(1,11):
    for j in range(i-1):
        print(' ', end='')
    for j in range(11-i):
        print('*', end='')
    for j in range(10-i):
        print('*', end='')
    print()

for y in range(2,10):
    for x in range(1,10):
        print('%3d' % (y * x), end=' ')
    print()

a = [4, 7, 100, 13]
result = []
for i in a:
    result.append(i * 3)
print(result)

result = [num * 3 for num in a]
print(result)