# -*- coding: utf-8 -*-
"""exam02_variable.ipynb의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y9VxmMSy_6SrbVY2Ab4qf7ztm-RktD6T

#변수

##숫자형
"""

10 + 20

"""python에서의 변수 활용"""

a = 10
b = 20
PI = 3.1415

print(a)

print(type(a))
print(type(PI))

"""####사칙연산"""

sum = a + b
print(sum)

sub = a - b
print(sub)

print(a * b)

print(a / b)

"""몫 연산자 : //"""

print(a // b)

"""나머지 연산자 : %"""

print(a % b)

"""##List"""

a = []
b = [1, 2, 3]
c = ["Life","is", "too", 'short']
d = [1, 2, "Life", "is"]
e = [1, 2, ['Life', 5]]

f = e[2][0:2]
print(f)

print(b[2])
print(d[2])
print(e[2][1])

print(b[-1])

a = [1, 2, 3, 4, 5]
b = a[0:3]
print(b)

b = a[:3]
print(b)

b = a[2:5]
print(b)
c = a[2:]
print(c)
d = a [2:4]
print(d)

a = [1, 2, 3]
b = [4, 5, 6]
c = a + b       #list 와 list b 이어붙이기
print(c)
"""
[1, 2, 3, 4, 5, 6]
"""
'''
여러줄 주석
'''

c = []
c.append(a[0]  + b[0])
c.append(a[1]  + b[1])
c.append(a[2]  + b[2])
print(c)

d = a * 3
print(d)

print(len(d))

a = [1, 2, 3, 4, 5]

a[2] = 10
print(a)

del a[2]
print(a)

a.append(10)
print(a)

a.append(3)
print(a)

a.sort()
print(a)

a.reverse()
print(a)

print(a.index(10))

a.insert(1, 11)
print(a)

a.append(5)
print(a)

a.remove(5)
print(a)

a.remove(5)
print(a)

b = a.pop()
print(a)
print(b)

b = a.pop(1)
print(a)
print(b)

a = [1, 2, 3, 4, 5, 1, 2, 1, 1]
print(a.count(1))

number = 1
number += 2
number = number + 2
print(number)

a = a + [4, 5]
print(a)

a += [4, 5]
print(a)

a.extend([4, 5])
print(a)

"""##String"""

a = ["H", "e", "l", "l", "o"]
print(a)

str_a = "Hello"
print(str_a)

print(a[2])
print(str_a[2])

print(type(a))
print(type(str_a))

str_b = str_a[:4]
print(str_b)

str_c = 'world'
print(str_c)

str_d = '''"Python is very easy." 
he says.'''

print(str_d)

food = 'Python\'s favorite food is perl'
print(food)

head = "Python"
tail = "is fun"
str_head_tail = head + " " + tail
print(str_head_tail)
print(head, tail)

a = "hobby"
print(a.count("b"))

a = "Python is the best choice"
print(a.find('o'))

print(",".join('abcd'))

s = " hi "
print(s.lstrip() + "there")
print(s.rstrip() + "there")
print(s.strip() + "there")

a = "Life is too short"
b = a.replace("Life", "Your leg")
print(a)
print(b)

str_list = a.split()
print(str_list)
print(type(str_list))

b = "car,baby,code,day"
str_list = b.split(',')
print(str_list)

"""##Tuple"""

t1 = ()
t2 = (1, )
t3 = (1, 2, 3)

print(t2 + t3)
t4 = t2 + t3 
print(t4)

"""##Dictionary"""

dic = {'name':'pey', 'phone':'0119993323', 'birth': '1118'}

print(dic['phone'])

dic[1] = 'hello'
print(dic)

dic['name'] = 'jerry'
print(dic)

del dic['phone']
print(dic)

job = {"김연아":"피겨스케이팅", "류현진":"야구", 
       "박지성":"축구", "귀도":"파이썬"}
print(job)

print(job['류현진'])

print(job.keys())

print(job['귀도'])

print(job.values())

print(job.items())

print(job['류현진'])
print(job.get('손흥민'))

print('류현진' in job)
print('손흥민' in job)

"""##Set"""

s = set([1,2,3,3])
print(s)
#print(s[2])

s1 = set([1,2,3,4,5,6,7,8])
s2 = set([5,6,7,8,9,10,11,12])

intersection = s1 & s2
print(intersection)

intersection = s1.intersection(s2)
print(intersection)

union = s1 | s2
print(union)

union = s1.union(s2)
print(union)

difference = s1 - s2
print(difference)
difference = s2 - s1
print(difference)

print(s1.difference(s2))
print(s2.difference(s1))

print(True and False)
print(True or False)
print(True & False)
print(True | False)

s1 = set([1,2,3,4,5,6,7,8])
print(s1)
s1.add(9)
print(s1)
s1.update([10,11,12])
print(s1)

s1.remove(4)
print(s1)

a = 10
b = 10
c = 20
print(a == b)
print(a == c)
print(a < b)
print(a > b)
print(a <= b)
print(a >= b)
print(a != b)

"""##변수"""

a = [1, 2, 3]
print(id(a))

b = a
print(b)
print(type(b))

print(id(b))

b[1] = 4
print(a)

b = a[:]
print(b)

print(id(a))
print(id(b))

print( a is b)

a, b, c = 10, 20, 30
print(a)
print(b)
print(c)


print(a is b)

a = 10
b = 20
c = a
a = b
b = c
print(a)
print(b)

a, b = b, a
print(a)
print(b)

