# -*- coding: utf-8 -*-
"""exam04_function_3.ipynb의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ev0ezP0fUJ3qtYDRBro70EiOq6k4apfx
"""

celsius_value = 10
faherenheit_value = celsius_value * 1.8 + 32
print(faherenheit_value)

celsius_value = int(input('섭씨 온도를 입력하세요.\n'))
faherenheit_value = celsius_value * 1.8 + 32
print('화씨 온도로 %.2f입니다.' % faherenheit_value)

def celsius_to_faherenheit(celsius_value):
    result = celsius_value * 1.8 + 32
    return result

celsius_value = int(input('섭씨 온도를 입력하세요.\n'))
faherenheit_value = celsius_to_faherenheit(celsius_value)
print('화씨 온도로 %.2f입니다.' % faherenheit_value)

a = 10
b = 20
c = a + b
print(c)

def this():
    a = 10
    b = 20
    c = a + b
    print(c)
    return c

a = this()
print(a)

print(this() + 20)

def add(x, y):
    result = x + y
    return result

a = add(10, 20)
print(a)

def say_hi():
    print('Hi')
    return 0

a = say_hi()
print(a)

def divider(x, y):  #x를 y로 나눈 결과
    return x / y

print(divider(y=2, x=10))

def add_4(num4, num1=0, num2=0, num3=0):
    return num1 + num2 + num3 + num4

print(add_4(1,2,3,4))

print(add_4(1,2,3))

print(add_4(1,2))

print(add_4(2))

print(add_4(2,num3=4))

def add_all(*args):
    result = 0
    for i in args:
        result += i
    return result

add_all(1,2,3,4,5,6,7,8,9,10)

def print_kwargs(**kwargs):
    print(kwargs)

print_kwargs(name='foo', age=3)

def add_and_mul(a,b):
    return a+b, a*b

print(add_and_mul(10, 20))


a = 1
def vartest(a):
    a = a + 1
    return a
a = vartest(a)
print(a)

a = 1
def vartest():
    global a
    a = a + 1

vartest()
print(a)

def add(a, b):
    return a + b

print(add(1,2))

add_l = lambda a, b: a + b

print(add_l(3,4))

"""
def add(a,b):
    return a+b
와 동일하게 작동한다
"""

a = 10
b = a
a = None
print(b)

a = [1,2,3]
b = a
b[1] = 4
print(a)

a = [1,2,3]
b = a
a = [4,5,6]
print(b)

a = None
print(b)

a = 3
b = a
a = 4
print(b)

f = open('./content/hello.txt', 'w')
f.write('Hello world!\nHi there!')
f.close()

f = open('./content/hello.txt', 'r')
print(f.readline())
print(f.readline())
f.close()

f = open('./content/exam01_hello.py', 'r')
while True:
    line = f.readline()
    if not line: break
    print(line)
f.close()

f = open('./content/exam01_hello.py', 'r')
lines = f.readlines()
print(lines)
for line in lines:
    print(line)
f.close()

f = open('./content/exam01_hello.py', 'r')
data = f.read()
f.close()
print(data)

with open('./content/fool.txt', 'w') as f:
    f.write('Life is too short, you need python.')